version: '3.8'

services:
  # Redis Master
  redis-master:
    image: bitnami/redis:latest
    container_name: redis-master
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"

  # Redis Replica 1
  redis-replica-1:
    image: bitnami/redis:latest
    container_name: redis-replica-1
    restart: always
    depends_on:
      - redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master

  # Redis Replica 2
  redis-replica-2:
    image: bitnami/redis:latest
    container_name: redis-replica-2
    restart: always
    depends_on:
      - redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master

  # Redis Sentinel 1
  redis-sentinel-1:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-1
    restart: always
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26379:26379"

  # Redis Sentinel 2
  redis-sentinel-2:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-2
    restart: always
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26380:26379"

  # Redis Sentinel 3
  redis-sentinel-3:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel-3
    restart: always
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "26381:26379"