// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	Password    string
	LatestLogin pgtype.Timestamp
	LatestJoin  pgtype.Timestamp
}
